# Generated by Django 2.1.11 on 2023-02-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_auto_20190722_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordPackageClazzMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=2)),
                ('package', models.CharField(max_length=200, null=True)),
                ('clazz', models.CharField(max_length=50, null=True)),
                ('method', models.CharField(max_length=50, null=True)),
                ('remark', models.TextField(null=True)),
            ],
            options={
                'db_table': 'KeywordPackageClazzMethod',
            },
        ),
    ]
