# Generated by Django 2.1.11 on 2023-02-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_keywordpackageclazzmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordClazz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.IntegerField()),
                ('clazz', models.CharField(max_length=50)),
                ('remark', models.TextField(null=True)),
            ],
            options={
                'db_table': 'KeywordClazz',
            },
        ),
        migrations.CreateModel(
            name='KeywordMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.IntegerField()),
                ('clazz', models.IntegerField()),
                ('method', models.CharField(max_length=50)),
                ('remark', models.TextField(null=True)),
            ],
            options={
                'db_table': 'KeywordMethod',
            },
        ),
        migrations.CreateModel(
            name='KeywordPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=200)),
                ('remark', models.TextField(null=True)),
            ],
            options={
                'db_table': 'KeywordPackage',
            },
        ),
        migrations.DeleteModel(
            name='KeywordPackageClazzMethod',
        ),
    ]
